### ISSUE TITLE
titlebar min, max, and close buttons are normal, not themed

### ISSUE THREAD

**Issue by herbanonymous** [catppuccin/firefox#13]
When using the Catppuccin Mocha - Lavender 2.0, Minimize, Maximize, and Close buttons are normal, not themed.

![catppuccin-mocha-lavender](https://user-images.githubusercontent.com/126644856/222052179-8eddff68-b238-4a68-b27d-bfbcf20418d7.png)

When using the System theme - auto 1.3, buttons are themed, not normal.

![system-theme-auto-catpuccin-mocha-standard-lavender-dark](https://user-images.githubusercontent.com/126644856/222052957-26eed4f1-c2be-4c7d-82f2-d698a129deea.png)

My gtk theme is set in `gnome-tweaks` to Catppuccin-Mocha-Standard-Lavender-Dark, which I generated with `python3 install.py mocha -a lavender -l` on main branch of [catppuccin/gtk](https://github.com/catppuccin/gtk).

Mozilla Firefox: 109.0.1 
OS Name: openSUSE Tumbleweed 
OS Type: 64-bit 
GNOME Version: 43.3 
Windowing System: Wayland

My question, which theme should I use for the Catppuccin experience the developers intended? I assume the official theme, which is more colorful. However, the auto theme is also pretty, and themes the buttons. My _real question_ is how to make the official theme's buttons like the system theme. I like the official theme better in every way with the exception of the buttons being unthemed.

**Comment by isabelincorp** [comment]
Fixed with #15, you'll need to install the Firefox Color extension or wait for the store themes to be updated (I'll get to it by the end of August).
