### ISSUE TITLE
unable to view bookmarks

### ISSUE THREAD

**Issue by kishy-codes** [catppuccin/firefox#14]
the text color in not inverting when choosing bookmarks
![image](https://user-images.githubusercontent.com/106916795/227516409-df6aef8a-867c-4e2a-9571-9821c903eb43.png)

**Comment by kishy-codes** [comment]
or perhaps a different color should be used here

**Comment by kishy-codes** [comment]
after a bit of tinkering, i found out that "sidebar highlight" is the color that's suppose to change

**Comment by kishy-codes** [comment]
or you could change the "sidebar highlight text" to black, which fixes the issue maintaining the accent

**Comment by unseen-ninja** [comment]
**Sidenote:** This currently only applies to the [🔧 Custom Install](https://github.com/catppuccin/firefox#-custom-install) way.
