### ISSUE TITLE
Firefox theme overrides the window buttons

### ISSUE THREAD

**Issue by nahharris** [catppuccin/firefox#18]
I'm using the catppuccin theme for gnome and also the theme for firefox. With just the gnome theme enabled, i get this:

![image](https://github.com/catppuccin/firefox/assets/25548355/0cd5f0a3-c298-43f8-82cb-7c03e3d11aa4)

When enabling the firefox theme, those buttons ignore the gnome theme

![image](https://github.com/catppuccin/firefox/assets/25548355/91cc2b61-d8c1-4acc-aed6-6cdae41aa511)

Is it something you guys can fix?

**Comment by isabelincorp** [comment]
Hi, thanks for opening the issue!
Apologies for the long wait, but I found a solution!

In the `about:config` tab of Firefox, go to `widget.gtk.non-native-titlebar-buttons.enabled` then set it to `false`

Before:
![image](https://github.com/user-attachments/assets/19b4cc1a-639b-4c05-b3fa-4e9b325d64cd)


After:
![image](https://github.com/user-attachments/assets/1220fc5f-dc67-4e10-a7d2-876a5937b294)

Source: https://github.com/mattmess1221/firefox-gtk-controls

**Comment by nahharris** [comment]
Thx, it was so long ago that i changed Ubuntu for Debian, then stoped using Firefox to use Chromium, then Vivaldi, then Opera and now Zen

Thankfully Zen is firefox based so your solution still works with the Zen catppuccin theme

Thank you very much
